#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from urllib.parse import urlencode

import httpx

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from packages.public_records.config import (  # noqa: E402
    DATA_CITY_BASE,
    bis_url,
    building_bbl_compact,
    building_bin,
    building_borough,
    dob_now_public_portal_url,
    source_configs,
)


DEFAULT_DEVICES = ("3P6189", "3P6190")


class VerificationError(RuntimeError):
    pass


def _format_template(value: str, *, device_1: str) -> str:
    return value.format(
        bbl=building_bbl_compact(),
        bin=building_bin(),
        borough=building_borough(),
        borough_upper=building_borough().upper(),
        device_1=device_1,
    )


def _query_url(dataset_id: str, params: dict[str, str]) -> str:
    return f"{DATA_CITY_BASE}/resource/{dataset_id}.json?{urlencode(params)}"


def _get_json(client: httpx.Client, url: str, params: dict[str, str] | None = None):
    response = client.get(url, params=params)
    response.raise_for_status()
    payload = response.json()
    if isinstance(payload, dict) and payload.get("error"):
        raise VerificationError(f"{url} returned Socrata error: {payload.get('message')}")
    return payload


def _columns(client: httpx.Client, dataset_id: str) -> set[str]:
    payload = _get_json(client, f"{DATA_CITY_BASE}/api/views/{dataset_id}/columns.json")
    out = {row.get("fieldName") for row in payload if isinstance(row, dict) and row.get("fieldName")}
    if not out:
        raise VerificationError(f"{dataset_id}: metadata returned no columns")
    return out


def _metadata(client: httpx.Client, dataset_id: str) -> dict:
    payload = _get_json(client, f"{DATA_CITY_BASE}/api/views/{dataset_id}")
    if not isinstance(payload, dict) or not payload.get("name"):
        raise VerificationError(f"{dataset_id}: metadata lookup failed")
    return payload


def _count(client: httpx.Client, dataset_id: str, params: dict[str, str]) -> int:
    payload = _get_json(client, f"{DATA_CITY_BASE}/resource/{dataset_id}.json", {"$select": "count(*)", **params})
    if isinstance(payload, list) and payload:
        return int(payload[0].get("count", 0))
    return 0


def _sample(client: httpx.Client, dataset_id: str, params: dict[str, str]) -> list[dict]:
    payload = _get_json(client, f"{DATA_CITY_BASE}/resource/{dataset_id}.json", {"$limit": "5", **params})
    if not isinstance(payload, list):
        raise VerificationError(f"{dataset_id}: sample query returned non-list payload")
    return payload


def _render_doc(results: list[dict], *, output_path: Path) -> str:
    lines: list[str] = [
        "# Public Record Sources",
        "",
        "Generated by `scripts/verify_nyc_sources.py` from NYC Open Data metadata and sample API calls.",
        "",
        "## Building",
        "",
        f"- Address: 455 Ocean Parkway, {building_borough()}, NY",
        f"- BBL: `{building_bbl_compact()}`",
        f"- BIN: `{building_bin()}`",
        f"- DOB NOW Public Portal: {dob_now_public_portal_url()}",
        f"- BIS: {bis_url()}",
        "",
        "## Sources",
        "",
    ]
    for result in results:
        source = result["source"]
        lines.extend(
            [
                f"### {source['name']}",
                "",
                f"- Key: `{source['key']}`",
                f"- Dataset ID: `{source['dataset_id']}`",
                f"- Official URL: {source['url']}",
                f"- API endpoint: {source['endpoint']}",
                f"- Elevator-specific: `{str(source['elevator_specific']).lower()}`",
                f"- Covers: {source['notes'] or 'See useful fields.'}",
                f"- Verified useful fields: `{', '.join(result['verified_fields'])}`",
                f"- Filter fields: `{', '.join(source['filter_fields'])}`",
                "",
                "| Query | Row count | Returned columns | Example URL |",
                "| --- | ---: | --- | --- |",
            ]
        )
        for query in result["queries"]:
            returned = ", ".join(query["returned_columns"]) if query["returned_columns"] else "(no rows)"
            lines.append(f"| `{query['label']}` | {query['row_count']} | `{returned}` | {query['url']} |")
        lines.append("")
        lines.extend(
            [
                "Store in `PublicRecordWatch`:",
                "",
                f"- `source_system`: `{source['key']}`",
                f"- `record_type`: `{source['record_type']}`",
                "- `record_key`: dataset-specific primary ID from the normalization layer",
                "- `raw_json`, `raw_hash`, `first_seen_at`, `last_seen_at`, `last_changed_at`",
                "- `machine_verification_status`, `machine_confidence`, `machine_verified_at`, `machine_verification_summary` from official-source matching",
                "- `needs_human_verification`: `true` only when official-source matching is weak, conflicting, or below the auto-verification threshold",
                "",
            ]
        )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines).strip() + "\n"
    output_path.write_text(text, encoding="utf-8")
    return text


def verify_sources(*, output_path: Path, timeout: float = 30.0) -> list[dict]:
    results: list[dict] = []
    device_1 = DEFAULT_DEVICES[0]
    elevator_job_filing_numbers: set[str] = set()
    errors: list[str] = []

    with httpx.Client(timeout=timeout, follow_redirects=True) as client:
        for source in source_configs():
            try:
                meta = _metadata(client, source.dataset_id)
                columns = _columns(client, source.dataset_id)
                missing = [field for field in (*source.required_fields, *source.useful_fields, *source.filter_fields) if field not in columns]
                if missing:
                    raise VerificationError(f"{source.dataset_id} missing expected fields: {', '.join(sorted(set(missing)))}")

                queries: list[dict] = []
                templates = list(source.query_templates)
                if source.key == "dob_now_elevator_device_details" and elevator_job_filing_numbers:
                    templates.insert(0, {"job_filing_number": sorted(elevator_job_filing_numbers)[0]})

                for index, template in enumerate(templates, start=1):
                    params = {field: _format_template(value, device_1=device_1) for field, value in template.items()}
                    row_count = _count(client, source.dataset_id, params)
                    rows = _sample(client, source.dataset_id, params)
                    returned_columns = sorted({key for row in rows for key in row.keys()})
                    url = _query_url(source.dataset_id, {"$limit": "5", **params})
                    queries.append(
                        {
                            "label": ", ".join(f"{key}={value}" for key, value in params.items()),
                            "row_count": row_count,
                            "returned_columns": returned_columns,
                            "url": url,
                        }
                    )
                    if source.key == "dob_now_elevator_applications" and (
                        params.get("bbl") == building_bbl_compact() or params.get("bin") == building_bin()
                    ):
                        for row in rows:
                            job = str(row.get("job_filing_number") or "").strip()
                            if job:
                                elevator_job_filing_numbers.add(job)

                results.append(
                    {
                        "source": {
                            "key": source.key,
                            "name": meta.get("name") or source.name,
                            "dataset_id": source.dataset_id,
                            "record_type": source.record_type,
                            "url": source.url,
                            "endpoint": source.endpoint,
                            "filter_fields": source.filter_fields,
                            "elevator_specific": source.elevator_specific,
                            "notes": source.notes,
                        },
                        "verified_fields": [field for field in source.useful_fields if field in columns],
                        "queries": queries,
                    }
                )
            except Exception as exc:
                errors.append(f"{source.key} ({source.dataset_id}): {exc}")

    _render_doc(results, output_path=output_path)
    if errors:
        raise VerificationError("\n".join(errors))
    return results


def main() -> int:
    parser = argparse.ArgumentParser(description="Verify NYC/DOB/Open Data source IDs and field names.")
    parser.add_argument("--output", default="docs/PUBLIC_RECORD_SOURCES.md")
    args = parser.parse_args()

    try:
        results = verify_sources(output_path=Path(args.output))
    except VerificationError as exc:
        print("NYC source verification failed:", file=sys.stderr)
        print(str(exc), file=sys.stderr)
        return 1

    print(f"Verified {len(results)} sources.")
    print(f"Wrote {args.output}")
    for result in results:
        counts = ", ".join(f"{query['label']}: {query['row_count']}" for query in result["queries"])
        print(f"- {result['source']['key']} ({result['source']['dataset_id']}): {counts}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
